version: "3"
services:
    app:
        build:
           context: .
        ports:
            - "8888"
        image: mcandemir/portfolio
            

    nginx: 
        image: nginx:latest
        depends_on:
            - app
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
    
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal -m mhmtcndmr01@gmail.com -d mehmetcandemir.com --agree-tos
