name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
        run: |
          docker login -u mcandemir -p $DOCKERHUB_TOKEN
      - name: Docker Image Build
        run: docker build -t mcandemir/portfolio:latest .
      - name: Docker Push
        run: docker push mcandemir/portfolio:latest
